name = "f2link"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "f2link"
database_id = "3787a4ee-2ffd-41bc-bbf9-e428c81bcf70"

[triggers]
crons = ["0 */6 * * *"]
